### ISSUE TITLE
Variance not passed to the centroiding function

### ISSUE THREAD

**Issue by amn3142** [sibirrer/psfr#6]
Not sure if this was intentional but the call to centroid_fit on lines 76 and 99 of psfr don't pass the variance (error_map) along.

**Comment by sibirrer** [comment]
good point! I think I just did not use it yet and so this feature was not passed down. Just pushed the changes such that it should work. Please close the issue if it works or let me know. Thank you!

**Comment by amn3142** [comment]
I'm now working with a mutant version of psfr because I also added emcee into the centroiding. There was probably some procedure I should have followed to get here... 

Anyway looks like current line 104 still missing the variance: 
https://github.com/sibirrer/psfr/blob/969dd3ad7514942bb9fef2499d6a261395cf9077/psfr/psfr.py#L104

**Comment by sibirrer** [comment]
oh, indeed.
You could have 'forked' the repo to your GitHub and then cloned it from there if you wanted to make changes. You can still do it and then make a pull request to get the changes (or part of it) added, such that our versions do not deviate too much from each other
